---
title: "STAT 7630, Homework 1"
author: "D. Pluta"
date: '2026-01-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Homework 1

1.  One Sample Normal Model
a. Write down the likelihood for $(y_1, \dots, y_n) \overset{iid}\sim \mathcal{N}(\mu, \sigma^2)$.
b. Derive the MLE of $\mu$ assuming $\sigma^2$ is known.
c. Derive the MLEs for $\mu$ and $\sigma^2$ when both are unknown.
d. Compute the bias for both of the MLEs you calculated in the previous part.

2. Using the UN11 life expectancy data from Weisberg, conduct a one-way ANOVA to 
test whether at least one of the country groups has a mean life expectancy that differs
from the others.  Compute the ANOVA table and clearly identify the P-value and 
the conclusion of the test.

3. Using the UN11 data, show the R code for reconstructing Table 6.1 in Weisberg.

4. Consider a sample of observations $y_{ij}, i = 1, \dots, I; j = 1, 2, 3$, 
where $i$ is the observation and $j$ is group.

  a. Verify the identify $SSTot = SSW + SSB$.
  b. Write the one-way ANOVA model, including any model assumptions.
  c. Write the null and alternative hypotheses for the one-way ANOVA model.
  d. Explain in words the interpretation of SSTOT, SSW, and SSB.
  
5. Simple Linear Regression
  a. Write the likelihood for SLR.
  b. Derive the MLE for the coefficient $\beta$, assuming the error variance is known.

6. Suppose a drug is tested at dosages $25 mg, 50 mg, 100mg$ against a placebo ($0 mg$). Researchers believe the 50mg dose may have a detrimental or neutral effect on the measured outcome.
  a. What method or model would you use to determine if the 50mg dose produces a lower response than the 25mg dose?
  b.  What method or model would you use to determine if the effect of the dose with the highest average response value has a significantly greater effect relative to the other dosages?
  c. Construct a linear regression model for the sample, assuming nothing is know regarding the relationship of the average response values at the different doses.